# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://69.30.252.106:8089/api/rate

<> 2018-09-15T091211.200.html
<> 2018-09-15T091200.405.html

###

POST http://69.30.252.106:8089/api/user?name=gdiq1&email=qeqwe@qewqwe123.com&password=secret&city=samara&country=russia&currency_code=EUR

###

PUT http://69.30.252.106:8089/api/wallet/1?amount=7&password=secret

###

POST http://69.30.252.106:8089/api/transfer?sender_password=secret&amount=12&sender_id=3&recipient_id=1&currency_code=RUB
Accept: */*
Cache-Control: no-cache

<> 2018-09-15T090927.200.html

###
